# Generated by Django 5.1.7 on 2025-07-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laboratory',
            options={'ordering': ['nome'], 'verbose_name': 'Laboratório', 'verbose_name_plural': 'Laboratórios'},
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='data_modificacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Modificação'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='status',
            field=models.IntegerField(choices=[(0, 'Disponível'), (1, 'Indisponível')], default=0, verbose_name='Status'),
        ),
    ]
