# Generated by Django 5.1.7 on 2025-03-20 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0003_model3d'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('editora', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_modificacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='model3d',
            options={'verbose_name_plural': 'Models 3D'},
        ),
    ]
