# Generated by Django 5.1.7 on 2025-03-20 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0004_livro_alter_model3d_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='localizacao',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
