# Generated by Django 5.1.7 on 2025-03-29 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0009_perfil_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='data_nascimento',
            field=models.DateField(null=True),
        ),
    ]
